env:
    global:
        - REPO_DIR=.
        # pip dependencies to _build_ your project
        - BUILD_DEPENDS="cython numpy"
        # pip dependencies to _test_ your project.  Include any dependencies
        # that you need, that are also specified in BUILD_DEPENDS, this will be
        # a separate install.
        - TEST_DEPENDS="numpy pytest"
        - UNICODE_WIDTH=32


# You will likely prefer "language: generic" for travis configuration,
# rather than, say "language: python". Multibuild doesn't use
# Travis-provided Python but rather installs and uses its own, where the
# Python version is set from the MB_PYTHON_VERSION variable. You can still
# specify a language here if you need it for some unrelated logic and you
# can't use Multibuild-provided Python or other software present on a
# builder.
language: python

# For CPython macOS builds only, the minimum supported macOS version and
# architectures of any C extensions in the wheel are set with the variable
# MB_PYTHON_OSX_VER: 10.9 (64-bit only) or 10.6 (64/32-bit dual arch). By
# default this is set to the highest available for the Python version selected
# using MB_PYTHON_VERSION. You should only need to set this explicitly if you
# are building a 10.6 dual-arch build for a CPython version where both a 10.9 and
# 10.6 build are available (for example, 2.7 or 3.7).
# All PyPy macOS builds are 64-bit only.

# Required in Linux to invoke `docker` ourselves
services: docker

# Host distribution.  This is the distribution from which we run the build
# and test containers, via docker.
dist: xenial

matrix:
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - MB_ML_VER=2014
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - MB_ML_VER=2014
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - MB_ML_VER=2014
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.9
        - MB_ML_VER=2014

before_install:
    - git clone https://github.com/matthew-brett/multibuild.git
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

before_deploy:
    - echo DEPLOYING
    - ls
    - mv wheelhouse zfp/dist
    - cd zfp
    - ls dist

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "1w5OdXdfDiJTUTIwLkUzYujyfMBEc8qJMh1HaWSOyna5279idy/SNFYW+unYAL/w/dZh8JWPY0knexrmpFlBPVgfzXNszrCfZKnDIiimE1tVjP05Hc7OxqoS/yRfZGFsKe8T2tMc9WKLAOltUbb/vPrY2ohGDmavL1h23JElrHnLXlstXXdo/EwptpVca+l8a9UAX8L6g2pcNQU3h4BPWWonEPhHbGoHIBJVyzA4QRsWiPl8rXN2NQCZ30z9JVvXOv7+mROw1o7MHCgPhUq8nb+ui4f5QR2t26PHKZXPUEN/0HHGeh8lmT2bmTrMCDQvh2nG1bsHTft4fnej6tgZG5Dh3V/Qfz6VSPZHlTQjI753c6+IAUOvjEBXtVZaNJOKSCpzAPtufdxRxOe95qPEPHrM8B+KWi3E5KVouubq8c8knOVBYBRX8Q0+JgIZxK2aqkzcIJ8PmPPNL5wZgRIS/axEroqDpqXKhy+qiD04Fhc4bKh9jtLb59xmswl+fHt8benQcId7pgAoO+FldBkMt080XM79EXgYwhCV6+dk2DSoQNoYtHgR2irrbvo40IDgJ16KN4vvZiaJcI6oiZNh05xhnMCVNHf5xiI6tR7sfPVII99S0fwss4W2Ks2qsf9de2+zsZo8a8ugPEB+TYrUDWyjXMgKNp0Za8Xb97lUja4="
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
